[project]
name = "covid-worldwide"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "dash",
    "dash-bootstrap-components>=2.0.4",
    "gunicorn>=25.0.3",
    "numpy>=2.4.2",
    "pandas<3.0.0",
    "statsmodels>=0.14.6",
]
